version: '{build}'
image: Visual Studio 2017
configuration: Release
pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - master
nuget:  
  disable_publish_on_pr: true
init:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
          Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
      }
build_script:  
  - ps: .\Build.ps1
test: off
artifacts:  
  - path: '.\src\FootballDataApi\artifacts\*.nupkg'
    name: NuGet
deploy:  
- provider: NuGet
  name: production
  api_key:
    secure: oy2lolnwvfhe47lska4q22s3mq7rsvre5ashv2de5gkcou
  on:
    branch: master